version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ruslan
      POSTGRES_PASSWORD: password
      POSTGRES_DB: contacts_db
    ports:
      - "5432:5432"

  app:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://ruslan:password@db:5432/contacts_db
